# Collaborations

<br>

Collaborative science is a hallmark of the W.A.D.E. Lab and as such, it's important to establish some ground rules when working with others. In so doing, there are generally three types of objectives:

1) Your needs as an individual (eg, professional advancement, mental health);

2) Project objectives (eg, preserving project timeline, producing all project deliverables);

3) Team cohesion (eg, preserve team harmony, preserve relationships with specific members that you will likely work with again).

Each of these may be top priority at different times or in different types of conflict, but be aware of which one you (and other team members) are prioritizing and which, if any, are being deprioritized.

[Click here](https://docs.google.com/presentation/d/1_8Dt204Onja83bx5QjLAaHGiU2hPP1ImQH1gldVzVdo/edit?ts=5f3ed056#slide=id.g7dbff98225_0_98) to view a collection of slides that Kelly Mistry put together to help navigate this process.

## Memorandum of Understanding

As many research projects within the W.A.D.E. Lab will involve samples or data shared from a state or federal agency, a first step in the process will be writing and signing a memorandum of understanding that will govern the use of the shared data, as well as expected deliverables and paper authorship where appropriate. A general template MOU can be found [here](). The student will be responsible for initiating the development of this MOU, and it will be signed by Amy, the student, and at least one agency representative. The student will be expected to share a copy of the signed, finalized MOU with Amy and the agency, and will keep a copy in their records.