# Expectations

<br>

People in the Whale and Dolphin Ecology Lab are expected to be good citizens, neighbors, and office/lab mates. Please try your best to act in a manner consistent with our [Code of Conduct] as well as the [SAFS Code of Conduct](https://fish.uw.edu/about/code-of-conduct/).

## Amy's role

Amy serves as a mentor and source of information about academics, research, service, and life in general. She will do her best to help everyone get the most out of their experience at SAFS and UW. Amy will push you to be your best self, which may include some uncomfortable conversations on occasion. Maintaining open and clear lines of communication will be paramount to our successful mentor/mentee relationship. As such, Amy believes strongly that students, postdocs, and technicians should feel empowered to openly express their feelings.

Although Amy is committed to helping you find the resources and information you need, she's also cisgendered, straight, and white, which means some of you may want to seek advice from others inside or outside of SAFS. If you should choose to do so, you are under no obligation to tell Amy about it.

### Some things to expect from Amy {-}

* Amy will strive to be impartial in her dealings with all lab members and cultivate a welcoming and inclusive atmosphere to facilitate learning and excellence.

* Amy will endeavor to be clear in his advice and feedback to you.

* Amy will help you select a thesis topic and plan your research, which includes advice on possible supervisory committee members and courses that will help you now as well as in your future career.

* Amy will monitor your progress towards your academic and professional goals and provide feedback intended to help you achieve those goals.

* Amy will respond to any requests for help and meetings within 24 hours (except in exceptional circumstances).

* Amy will keep you informed regarding your current funding and will work with you to find future funding.

* Amy will provide career advice and help you expand your professional network. 

* Amy will assist you in finding a position following the completion of your program, which includes writing honest letters of recommendation on your behalf.

## Grad students

Graduate school should be a rewarding experience, but it can be incredibly challenging at times. The resources provided here are meant to help you transition to a new phase in your life and get the most out of your time at the UW School of Aquatic and Fishery Sciences. Staying organized with respect to your personal obligations, coursework, research, and outreach will help you through the process.

As a new graduate student in our lab, you will be welcomed into a group of diverse individuals with varying interests. We support each other in our respective endeavors and celebrate our successes. You will have numerous opportunities to contribute to our research projects, develop lasting bonds to others within and outside the lab, and help us improve upon our ways.

### Things Amy expects from you {-}

* You will maintain a high level of professionalism, which includes acting ethically and behaving in a manner consistent with our lab's [Code of Conduct](https://scheuerell-lab.github.io/lab-book/code-of-conduct.html) and the [UW Student Conduct Code](https://www.washington.edu/admin/rules/policies/WAC/478-121TOC.html).

* You will ask Amy for clarification on anything that is unclear or confusing.

* You will know the requirements of your degree program, including important milestones such as coursework, committee formation, and proposal submission. 

* You will attend all relevant meetings and seminars, including weekly SAFS seminars, lab meetings and one-on-one meetings with Amy.

* You will come prepared to any meetings we have, which includes a clear idea of the agenda or goals for the meeting.

* You will keep careful notes of your research and meetings, and ensure that you research data and software are backed up. 

* You will keep Amy apprised of your academic progress.

* You will ensure that your supervisory committee is kept informed about your research and you will organize meetings with your supervisory committee at least annually.

* You will carefully review Amy's comments on drafts of your work (not simply “accept all”) and question me if a suggestion for a change is unclear or does not seem justified/appropriate.

* You will use your peer network to find and receive advice, to the extent possible.

### Mentoring plans {-}

All grad students will develop a mentoring plan with assistance from Amy. This will be a "living document" that evolves over time according to the goals and needs of the student.

### Annual reviews {-}

All grad students will undergo an annual review with Amy, which involves the following 3 steps, as outlined [here](https://fish.uw.edu/wp-content/uploads/sites/29/2020/06/GSAR.pdf):

1. Independent reports

    * Student and Advisor both complete Annual Review reports, which include a self assessment

2. Student / Advisor meeting

    * Meet to discuss independent review reports

    * Define specific goals for the next academic year including any planned exams

    * After meeting, the advisor will distribute both reports to Committee

3. Committee meeting

    * Meet to discuss independent reports or distribute them electronically

    * Revise and/or approve goals for next academic year

    * Committee discusses and completes the Annual Committee Meeting Report, and sends it to Student for a response

    * Advisor files completed Committee Report with SAFS


## Postdocs

Post-docs in our lab conduct independent research and serve as *ad hoc* advisors to undergraduate and graduate students. They are a useful source of information and can help students navigate difficult situations.

### Annual reviews {-}

All postdocs will undergo an annual review with Amy, as required under the collective bargaining agreement. Prior to the meeting, Amy (and potentially other collaborators) will fill out [this form](resources/postdoc_360.docx). The postdoc will fill out [this form](resources/postdoc_annual_activities.docx). After the meeting, Amy will send the completed forms to the HR director and they will file them away.


## Undergraduates

Undergraduate research experiences are an important part of setting people up for success in future scientific endeavors, especially if they are interested in attending graduate school. Our lab employs undergraduate technicians for lab and field work, and we also sponsor undergraduate students working on their senior capstone projects in [SAFS](https://fish.uw.edu/students/undergraduate-program/degree-overview-new/undergraduate-capstone-project/) and the [Program on the Environment](https://envstudies.uw.edu/capstone-experience/). If you're an undergraduate working with our lab group, it's important that you understand the background and rationale for your project. Could you explain it equally as effectively to both Amy and your parent(s)?

Here are some additional expectations:

* We expect people working with us to be on time, so let us know ASAP if something comes up and you cannot be somewhere at a pre-specified time.

* Tell us if you break or lose something, which tends to happen from time to time and is a normal part of research. Your first concern should be for your safety and for those around you. Once you're sure everyone is OK, assess the situation and get help as needed. **If there is any sort of emergency, call 911 immediately**.

* We expect people to work the hours they're being paid. You may not do homework, read material unrelated to the lab, eat lunch, etc while being paid by us. You are welcome to use the lab space as a place to sit while you work on other tasks, though.

* Please clean up after yourself. The lab is a shared space and we do not want to suffer a [tragedy of the commons](https://en.wikipedia.org/wiki/Tragedy_of_the_commons). If you don't know where something belongs, ask for help.


## Work hours

Everyone is expected to work 40 hours a week and to finish their tasks on time, but there are no fixed hours when people are expected to be working in the office, lab, or remote location. That said, there will indeed be times when you are expected to be somewhere at a certain time, whether it be for a meeting, seminar, or lab/field work. Please be considerate of other people's time and do not make them wait for you or wonder where you are. If something should come up, please contact others to let them know your status.

*Remote Work:* COVID has taught us much about the benefits and limitations of remote work. Amy encourages remote work to the extent that it facilitates each lab member's personal productivity. However, Amy also recognizes that building and maintaining a professional network is important at every career stage, and that collaborative professional relationships improve the quality of everyone's scientific products. Amy expects that all of the members of the UW W.A.D.E Lab will work in the lab at least 3 days per week, in order to provide each lab member with *ad hoc* opportunities to form and maintain professional relationships within the SAFS and UW academic communities.

In general, Amy tries to maintain core hours at SAFS from 11:00-4:00 Monday-Thursday, so that people can interact with her on an *ad hoc* basis. When Amy knows she will be away due to travel or other business, she will do her best to alert the lab prior to her absence. If you cannot find Amy in her office, please send her a message via email or text message (if urgent or an emergency). You can also set up a one-off meeting with her using her [meeting scheduler](https://calendar.app.google/6S7FAok44L6n2TpF7).

If you are funded as an RA or TA, you are expected to work on the research program funding you, or the class to which you have been assigned, for 20 hours per week. You are expected to spend another 20 hours per week working on your own research, coursework, outreach, etc. "Side projects" are encouraged, but they should be considered part of your own 20 hours of research/studies, and not your RA or TA responsibilities. Your highest priorities are completing the tasks related to your TA/RA work and making progress towards completing your degree.


## Time off

*Everyone* in the lab is entitled to some time off from work. No one is expected to work on the following holidays:

* New Year's Day (January 1)  
* Martin Luther King, Jr. Day (third Monday in January)  
* Presidents' Day (third Monday in February)  
* Memorial Day (last Monday in May)  
* Juneteenth  (June 19)  
* Independence Day (July 4)     
* Labor Day  (first Monday in September)  
* Veterans' Day (November 11)  
* Thanksgiving Day (fourth Thursday in November)  
* Native American Heritage Day (fourth Friday in November)  
* Christmas Day (December 25)  

Note, too, that people are allowed to take up to two unpaid holidays per calendar year for a reason of faith or conscience, or for an organized activity conducted under the auspices of a religious denomination, church or religious organization.

### Grad students {-}

Grad students with a 50% or greater FTE appointment for twelve months are allowed 4 weeks (20 business days) of paid time off per year, but they should clear any leave plans with Amy at least 2 weeks in advance. There will be no reduction in pay or benefits for this time off. Grad students with a 50% appointment for less than twelve months, or those who are appointed for less than 50% FTE, shall have vacation time off prorated on this basis. 

Grad students who are employed as a 50% FTE for three or more quarters during the 12-month period starting September 16th shall be entitled to one personal holiday during that 12-month period (this applies to most students). Personal holidays must be requested in advance. Grad students are also eligible for paid sick leave, which accrues at one (1) hour for every 40 hours worked. Sick leave accrues at the end of the month and is available for use the following month.

More information about leave policies for grad students can be found [here](https://hr.uw.edu/labor/academic-and-student-unions/uaw-ase/ase-contract).

### Postdocs {-}

Postdocs receive 21 days of paid vacation time off at the beginning of the month following the start of each one-year appointment period. For appointment periods of less than one year, postdocs will receive the prorated number of paid vacation days. Unused vacation time off shall lapse 12 months from the date it was received and at the expiration of each appointment period. Unused vacation time off is not paid at separation, does not transfer between employment programs, and is not eligible for shared leave donation.

Postdocs receive one day of paid sick time off for every month of their appointment. Paid sick time off will be preloaded annually and available at the beginning of the month following the start of the appointment. Up to 12 days of unused sick time off will carry forward to the next appointment year. Note, however, that unused sick time off is not paid at separation, does not transfer between employment programs, and is not eligible for shared leave donation. 

More information about leave policies for postdocs can be found [here](https://hr.uw.edu/labor/academic-and-student-unions/uaw-postdocs/uaw-postdoc-contract).

## Absences

*Everyone* in the lab is responsible for letting Amy know if you will be away for an extended period of time, whether it be a personal vacation or for field work. If it's just a day off here or there, it's not a problem, but Amy and others would like to know ahead of time if you are likely to be difficult to get a hold of should we need to for any reason. We genuinely care about the well being of one another, so if you are absent for more than 2 days without notifying anyone, we will reach out to your emergency contact(s) to verify you are safe and well.

