--- 
title: ""
author: "Amy Van Cise"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: ""
---

```{r echo = FALSE}
## thanks to John Helveston for these functions
## https://github.com/jhelvy/jhelvy.github.io/blob/master/R/functions.R
make_icon <- function(icon) {
  return(htmltools::tag("i", list(class = icon)))
}

make_icon_text <- function(icon, text) {
  return(htmltools::HTML(paste0(make_icon(icon), " ", text)))
}

# Creates the html to make a button to an external link
icon_link <- function(icon = NULL, text = NULL, url = NULL) {
  if (!is.null(icon)) {
    text <- make_icon_text(icon, text)
  }
  return(htmltools::a(href = url, text, class = "icon-link"))
}
```

# Welcome {-}

<br>

This is the lab book for [Amy Van Cise](https://fish.uw.edu/faculty/amy-van-cise/)'s [Whale and Dolphin Ecology](amyvancise.com) (W.A.D.E.) Lab in the [School of Aquatic and Fishery Sciences (SAFS)](https://fish.uw.edu/) at the University of Washington. This book lays out the policies and procedures that we follow, serving as reference material for on-boarding, expectations, communications, coding, data, publishing, and presentations.

Research in the W.A.D.E. Lab focuses on understanding the ecology and evolution of top marine predators using integrative datasets to get at complex system processes. We like to tackle fundamental questions about how social behavior, as an ecological strategy, affects the evolutionary trajectory of top marine predators. We also focus a lot of our research on applied conservation questions such as how social behavior affects disease transfer and microbial similarity, or diet preferences and hunting strategies. We specialize in analyses using 'omics tools such as genomics, microbiomics, and eDNA, as well as passive acoustic data and photo ID data. You can read more about our research projects on our [lab website](https://www.amyvancise.com/current-research).

## Land acknowledgment {-}

We acknowledge the ancestral homelands of those who walked here before us and those who still walk here, keeping in mind the integrity of this territory where area Native peoples identify as the Duwamish, Suquamish, Snoqualmie, and Puyallup, as well as the tribes of the Muckleshoot, Tulalip, other Coast Salish peoples, and their descendants. We are grateful to respectfully live and work as guests on these lands with the Coast Salish and Native people who call this home.

## Credits {-}

Many people and sources inspired the content here. In particular, we would like to acknowledge [Mark Sheuerell](https://fish.uw.edu/faculty/mark-scheuerell/), who generated the original content and bookdown structure that this lab guide as based on. His work, in turn, was influenced by [Gavin Fay](https://sites.google.com/site/gfay42/), [Chelsea Wood](https://fish.uw.edu/faculty/chelsea-wood/), [Steven Roberts](https://fish.uw.edu/faculty/steven-roberts/), [Sarah Converse](https://fish.uw.edu/faculty/sarah-converse/), and many members of the Applied Ecology Lab. Our lab logo was designed by the wonderfully talented [Uko Gorter](https://ukogorter.com/), who is one of the world's foremost artists in the field of marine mammal scientific illustration.

If you have questions or suggestions for improvements, please contact [Amy Van Cise](mailto:avancise@uw.edu).


## License {-}

`r icon_link(icon = "fas fa-balance-scale", text = "CC-BY-SA-4.0 License", url  = "https://github.com/UW-WADE-lab/Lab-Guide/blob/main/LICENSE")`

<!-- <br> -->

<!-- <center style="font-size:0.95rem">v`r format(Sys.Date(), '%y.%m.%d')`</center> -->

