# (PART) Lab & Field {-}

# In the lab

## W.A.D.E. Lab Genetics Program {-}

The W.A.D.E. Lab shares genetics laboratory space with the SAFS MERLab, which is jointly run by Drs. [Lorenz Hauser](https://fish.uw.edu/faculty/lorenz-hauser/) ([Marine Population Genomics Lab](https://faculty.washington.edu/lhauser/wordpress/)) and [Kerry Naish](https://fish.uw.edu/faculty/kerry-naish/) ([Applied Evolutionary and Ecological Genetics Lab](https://faculty.washington.edu/knaish/)). The lab is located on the second floor of the Marine Studies building ([MAR](https://www.google.com/maps/place/Marine+Studies+Building+(MAR)/@47.6525504,-122.3156089,19z/data=!3m1!5s0x549014f1fcfb9d01:0xc96981eca3b78cce!4m6!3m5!1s0x549014f1fced4987:0xc612428a54e06427!8m2!3d47.6524713!4d-122.314939!16s%2Fg%2F1hm4zq649?entry=ttu)).

The MERLab maintains an [email listserv](https://mailman12.u.washington.edu/mailman/listinfo/merlab-upstairs) and holds regular lab meetings. If you will be working in any of the MERLab facilities, please sign up for the listserv and plan to attend the lab meetings regularly.

## Genetics Lab Safety Training {-}

Any member of the W.A.D.E. Lab who uses the genetics laboratory facilities must first complete a lab orientation and safety training, consisting of an in-person walk-through of the lab spaces and several online training courses. Please read this entire page carefully before scheduling an in-person orientation with Amy.

Once you have completed the online training courses and the in-person orientation to the MERLab spaces, please complete and sign the UW [Lab Employee Safety Training Record](https://www.ehs.washington.edu/system/files/resources/lab-employee-safety-train-checklist.docx), and email a copy to Amy.

### UW Lab Safety Resources {-}

The UW Environmental Health and Safety Office maintains several helpful lab safety resources. It will be helpful for you to familiarize yourself with each of these; you can always refer back to them when you have specific lab safety questions.

1. [UW EH&S Laboratory Safety Program Office](https://www.ehs.washington.edu/research-lab/laboratory-safety)
2. [UW Lab Safety Manual - December 2023 edition](https://www.ehs.washington.edu/system/files/resources/lsm.pdf)
3. [UW EH&S Training Courses](https://www.ehs.washington.edu/training/training-course-selection-guides)

### Required Online Training {-}

The required online training courses will depend what work each person is doing. In general, most people conducting genetic work in the MERLab will need the following three courses, at a minimum:

1. [Fire Extinguisher Training - Online](https://www.ehs.washington.edu/training/fire-extinguisher-training-online)
2. [Managing Laboratory Chemicals - Online](https://www.ehs.washington.edu/training/managing-laboratory-chemicals-online)
3. [Eyewashes and Safety Showers - Online](https://www.ehs.washington.edu/training/eyewashes-and-safety-showers)

Once you have completed these training courses, you should see them appear on your list of completed training courses on the [UW EH&S Training Records](https://www.ehs.washington.edu/training-records) site within 1-2 business days. When you meet with Amy, discuss with her whether your anticipated labwork would require any additional UW EH&S training.

## MERLab spaces {-}

The MERLab is divided into three main areas to minimize contamination: (1) a DNA extraction lab (MAR 271), (2) a pre-PCR lab (MAR 274), and (3) a post-PCR lab (MAR 277). Genetic material and an equipment or supplies should only move in the direction 1-2-3 and never backwards. Once something has left the pre-PCR lab, for example, it can only go to the post-PCR lab and never return to the DNA extraction lab or pre-PCR lab. *Note that it is generally not advised to bring lab notebooks in and out of lab spaces.*

### DNA Extraction Lab (MAR 271) {-}

This lab is currently set up for DNA extractions of all types; low template DNA (e.g. eDNA, aDNA), degraded DNA (e.g. fecal DNA), or sensitive DNA (e.g. microbiome) extractions occur in the clean room (MAR 271A on the right). Supplies and equipment from other rooms should not enter this room unless they are thoroughly bleached and sterilized beforehand. 

### Pre-PCR Lab (MAR 272 and 274) {-}

This lab is currently used for tissue subsampling prior to DNA extraction, as well as setting up the first amplification PCR. Products from the DNA extraction lab may enter this lab; once they do they should not return to the DNA extraction lab. Products that leave this lab may go to the post-PCR lab but should not re-enter this lab after being in post.

### Post-PCR Lab (MAR 277) {-}

This lab contains all PCR machines and is set up for all post-PCR processing of samples, including gel electrophoresis and library preparation for metabarcode sequencing, shotgun sequencing, etc. This lab is the terminus of genetic processing at the MERLab; products enter this lab from the pre-PCR or DNA extraction labs and should not return to any other lab at any point.

## MERLab Safety Equipment Locations {-}

1. **Fire alarms and extinguishers** - there are three (3) fire alarms in the MERLab. The first is located in the lobby at the top of the main stairwell. The second is located next to the west building exit at the end of the elevator hallway, and the third is located to the right of the north building exit, next to MAR 276. There are also two fire extinguishers: one is located outside MAR 277 and the second is next to MAR 293 in the elevator hallway. In addition to these, two fire extinguishers are located inside MAR 277, next to each door, and one fire extinguisher is located in MAR 272-274 along the west wall.
2. **Emergency Showers** - there are two (2) emergency showers on the west side of the MERLab hallway, one outside MAR  and another outside MAR 277 (post-PCR). These are checked monthly to ensure functionality.
3. **Eyewash Stations** - each lab space has an eyewash station at one of the sinks. In MAR 271 (DNA extraction), the eyewash station is located in the sink in MAR 271B. In MAR 272-274 (pre-PCR), the eyewash station is located in the sink closest to the north door (MAR 274). In MAR 277 (post-PCR), the eyewash station is located in the sink on the south side of the room, facing the windows.
4. **Evacuation Routes** - Exits are located at both the south and north ends of the MERLab hallway, as well as the west end of the elevator hallway.
5. **Material Safety Data Sheets and Standard Operating Procedures** - MSDSs and SOPs for all chemicals stored in the lab can be found in the pre-PCR lab, on the shelf above the lab bench on the south wall (MAR 272). Exposure limits for all chemicals used in the lab can be found on their respective MSDS sheets.
6. **Chemical Spill Kit** - A chemical safety spill kit is located by the north door in the pre-PCR lab (MAR 274).
7. **First Aid Kit** - A first aid kit is located in the pre-PCR lab (MAR 272-274) at the west end of the center lab bench.

### Emergency Contact Numbers {-}

Emergency contact numbers can be found inside the door of each MERLab space (MAR 271, 274, and 277). In an emergency, contact any of the following:

<center>

```{r, fig.align = "center", echo=FALSE}
library(pander)

contacts <- data.frame(Name = c("Amy Van Cise", "Lorenz Hauser", "Kerry Naish", "Luke Tornabene", "Bryan Briones Otiz", "Anna Simeon", "Chris Setzke"), Role = c("W.A.D.E. Lab PI", "MERLab PI", "MERLab PI", "Fish Sysemtatics Lab PI", "PhD Student, MERLab", "PhD Student, MERLab", "PhD Student, MERLab"), Phone = c("781-686-6753", "206-709-9569", "206-720-0078","631-383-2496", "206-778-5496", "253-330-7731", "262-853-5451"))

pander(contacts)
```

</center>

### Personal Protective Equipment {-}

Anyone working in any genetics lab is required to use personal protective equipment, both for their own protection as well as for the protection of the samples. While in the lab, always use a lab coat and nitrile gloves. **Note:** *Lab coats should not leave the lab in which they are located, do NOT wear lab coats in the hallway between labs or in another lab space. Similarly, nitrile gloves should not be transferred between labs.*

**Lab coats** can be found in each lab space. In MAR 271, they are located along the west wall, farthest from the door. In the pre-PCR lab (MAR 272-274), they are located by the north door (MAR 274). In MAR 277, they are located by the back sink. All lab coats should be returned to these locations when not in use.

**Nitrile gloves** can be found in MAR 271 on the lowest shelf above the lab bench, in MAR 272-274 on the south wall next to the door, and in MAR 277 on the north wall above the gel electrphoresis bench.

## Equipment Safety {-}

Proper technique is important to ensure safety while using MERLab equipment. SOPs for specialized MERLab equipment can be found in the W.A.D.E. lab's [Genetic Lab SOPs folder](https://drive.google.com/drive/folders/180tIs4EQgK9JZVMmZvN0ap2sO8C149bk?usp=sharing).

Special considerations include:

1. Centrifuges: always ensure centrifuges are properly balanced, and double-check that the lid is tightly sealed before running the centrifuge.
2. PCR machines: always ensure the top lid is sealed before running a PCR machine.

## Chemical Safety {-}

While working in the MERLab, you may come in contact with potentially harmful chemicals. SOPs for MERLab chemicals can be found in the W.A.D.E. lab's [Genetic Lab SOPs folder](https://drive.google.com/drive/folders/180tIs4EQgK9JZVMmZvN0ap2sO8C149bk?usp=sharing). MSDS sheets for all chemicals are located in the pre-PCR lab (MAR 274) above the lab bench on the south wall, and exposure limits for all chemicals used in the lab can be found on their respective MSDS sheet.

The most common potentially harmful chemicals are:

1. **EtOH (ethanol):** Ethanol may be found in dilutions of 100%, 95%, or 70%. 100% ethanol is flammable and can be an irritant to the eyes or skin. It can also affect the respiratory tract if breathed for a long period of time. Safety information for ethanol can be found [here](https://fscimage.fishersci.com/msds/89308.htm). If you come in contact with ethanol, rinse the affected area thoroughly (e.g. eyewash station for eyes or soap and water on skin). Store 100% ethanol in the chemical storage cabinet rated for flammable materials, located beneath the north fume hood in MAR 274. Ethanol waste should be disposed of by pouring into a container that is labeled "EtOH waste". Ethanol waste generated during DNA extractions can be consolidated into a single container that is stored in the fume hood in MAR 271B; ethanol waste generated during post-PCR processing can be consolidated into a single container that is stored in the fume hood in MAR 277. Once these waste containers are full, they should be disposed of by contacting UW EH&S.

2. **Bleach:** Bleach may be found in dilutions of 100% or ~10%. 100% bleach is corrosive and can cause eye and skin burns. It is also harmful if inhaled. Safety information for bleach can by found [here](https://fscimage.fishersci.com/msds/91020.htm). If you come in contact with ethanol, rinse the affected area thoroughly (e.g. eyewash station for eyes or soap and water on skin). Undiluted bleach can be found in a tightly sealed container below each sinks, stored away from other chemicals. Bleach is used in the lab only for cleaning equipment and bench spaces, and usually in 10-15% dilutions. Bleach can be disposed of by pouring down the sink while diluting with plenty of running water.

## MERLab storage {-}
### Chemical storage {-}

All chemicals, including dilutions, must be properly labeled with the chemical makeup (e.g. 95% EtOH/ethanol), date, and proper chemical labels. All chemicals must be stored at or below eye level, on a shelf with edge support. 

1. **EtOH (ethanol)** is stored in MAR 274, in the chemical cabinet underneath the fume hood located at the north end of the room. 
2. **Acids** are stored in the chemical cabinet underneath the fume head next to the millipore sink (MAR 276). 
3. **Bases** are stored in the cabinets beneath the lab bench in MAR 276.

### Glassware storage {-}

All glassware must be stored on a shelf with edge support. Most glassware is cleaned and stored in MAR 276, which is connected to the pre-PCR labs (MAR 272-274). Glassware storage for each lab space is:

1. MAR271: glassware can be found on the shelf above the sink.
2. MAR272-274 (pre-PCR): all glassware for the pre-PCR lab is stored in MAR 276 along the north wall.
3. MAR277: glassware can be found above the sink on the north wall.

### Fridge and Freezer Facilities {-}

Various freezers and refrigerators are available for temporary storage of genetic materials and reagents. These include:

1. DNA extraction lab: MAR 271 has a mini fridge for pre-PCR reagents and DNA extraction reagents only.
2. pre-PCR lab: One -80C freezer is located next to MAR 272 door for sample storage. Three -20 freezers are also available: Freezer #5 is for sample storage, Freezer #4 is for DNA storage, and Freezer #3 holds DNA as well as pre-PCR primers and other reagents. In addition the these, there is a small upright freezer (Freezer #8), which holds XXXX. 
3. post-PCR lab: There are 2 -20C freezers in the post-PCR lab. The upright freezer is currently used to store post-PCR products, the chest freezer holds reagents for use in post-PCR processing.
4. MAR 276: This lab has one refrigerator (Fridge A) for the storage of temperature-sensitive reagents and supplies (e.g. spin columns).

#### -80C Freezer Safety {-}

Note that objects frozen in ultracold (-80C) freezers will cause burns that can damage your skin if you come into direct contact with them. *Always* use thermal gloves when accessing these freezers. 

When done accessing an ultracold freezer, ensure that all inner and outer doors are completely closed and properly latched.

## Use of Consumables {-}

The MERLab is run as a cost center, which allows its member labs to combine orders and reduce waste and additional expenses. The use of certain consumables is covered by a monthly fee to the MERLab; e.g. gloves, ethanol, agarose. Other consumables are ordered as needed; each person must keep track of the amount of these consumables they are using and report that use on a spreadsheet in each lab. The consumables that are ordered on a per-use basis include:

1. Pipette tips (all labs)
2. DNA extraction kits (DNA extraction lab)
3. e-gels (post-PCR lab)

## Lab SOPs {-}

Standard Operating Procedures (SOPs) exist for several lab protocols that are typically carried out in the MERLab. These include:

1. DNA Extraction (intro video [here](https://www.youtube.com/watch?v=gMl5Q1jnIpg))
2. PCR amplification (intro video [here](https://www.youtube.com/watch?v=matsiHSuoOw))
3. Gel electrophoresis (intro video [here](https://www.youtube.com/watch?v=TIZRGt3YAug))
3. Metabarcode library preparation (overview videos [here](https://www.youtube.com/watch?v=kv09Mhegzuw) and [here](https://www.youtube.com/watch?v=EI9rOtceSe8))
  **Once the library is prepared, it will be sequenced using Next Generation Sequencing, or NGS, usually on an Illumina MiSeq sequencer (overview video [here](https://www.youtube.com/watch?v=CZeN-IgjYCo))
4. AMPure bead clean-up (intro video [here](https://www.youtube.com/watch?v=zGV0SjCe0CU))
5. MinElute DNA purification and gel purification (intro video [here](https://www.youtube.com/watch?v=YC-75aUSf2M))
6. Sanger sequencing (intro video [here](https://www.youtube.com/watch?v=dVRB4CaLizc))

All lab SOPs, as well as SOPs for chemical and equipment found in the lab, can be found in the W.A.D.E. lab's [Genetic Lab SOPs folder](https://drive.google.com/drive/folders/180tIs4EQgK9JZVMmZvN0ap2sO8C149bk?usp=sharing).

## MERLab Etiquette {-}

- At the beginning of each day, the first person in the lab can turn on hall lights and lab lights and unlock lab doors. At the end of each day, the last person in the lab should turn off all lights and lock all lab doors.

-	Keep lab counter spaces clear of clutter. Return all lab equipment and chemicals that are not actively being used to their proper storage locations. Before and after using a lab bench, thoroughly wipe the bench and pipettes with 10% bleach followed by 95% EtOH.

-	With the exception of standard household cleaning supplies (windex, all purpose cleaner, soap etc) or 10% bleach and 95% EtOH for bench cleaning, all chemicals should be stored in the approprate chemical storage either under the fume hood or in the chemical storage lab bench.

-	All portable lab equipment (e.g. PCR racks, glassware) that has been used must be soaked for at least 10 minutes in 10% bleach, rinsed in DI water, and left out to air dry. Within several hours or the following day, return lab equipment to it's storage location.

- Non-portable lab equipment (e.g. centrifuge, PCR machines, vortexers, tube spinners) should be wiped with 10% bleach and 95% EtOH if any DNA extract or amplification project comes in contact with this equipment. Additionally, equipment should be wiped with 10% bleach and 95% EtOH every 2-3 months.

-	Follow this general guideline: "leave it as clean or cleaner than you found it."

-	Unless otherwise marked, all supplies and equipment in the lab are communal.

-	Never store samples or chemicals outside of the lab.

-	All samples placed in the freezer should be labeled with a date, sample contents, name of project, and the person responsible for the samples.

- At the end of a specific lab project, review all intermediate products stored in the fridge and freezer spaces and determine what, if anything, should be stored long-term. Throw out any unneeded intermediate products. Contact the MERLab or W.A.D.E. Lab PIs to discuss long-term storage of products that you wish to keep.

- Periodically conduct checks of the fridge and freezer spaces to ensure that you've removed any unneeded products, and that all of your products are appropriately labeled and stored in the proper location (e.g. on your shelf, clearly labeled with your name).
