# Publications

<br>

Writing is a large part of our scientific endeavors, and as a member of our lab you should expect to be integrally involved in communicating the results of your research. Writing can be hard and it may take a lot of practice before one feels confident in their ability to communicate clearly and effectively. Amy is willing to help you with the writing process, but she will not write things for you.

## Authorship

Our research typically involves a wide variety of collaborators. When deciding who should be included as an author on any publication, we will follow APA guidelines, which state:

> Authorship credit should reflect the individual's contribution to the study. An author is considered anyone involved with initial research design, data collection and analysis, manuscript drafting, and final approval. However, the following do not necessarily qualify for authorship: providing funding or resources, mentorship, or contributing research but not helping with the publication itself. The primary author assumes responsibility for the publication, making sure that the data are accurate, that all deserving authors have been credited, that all authors have given their approval to the final draft; and handles responses to inquiries after the manuscript is published.

Authorship will be discussed prior to the beginning of a new project, so that expectations are clearly defined. However, changes to authorship may occur over the course of a project if a new person becomes involved or if someone is not fulfilling their planned role. In general, Amy expects that graduate students and postdocs will be first authors on publications on which they are the primary lead, and Amy will be the last author. Other authors will be listed in order of contribution, unless the author list becomes very large - in those cases, all other authors can be listed in alphabetical order.

### Affiliation

W.A.D.E. lab members should list their affiliation as

> School of Aquatic and Fishery Sciences  
> University of Washington  
> Seattle, WA

## Peer-reviewed

Most of what we write is destined for publication in peer-reviewed journals.

## Old projects

For projects that required significant lab resources (e.g., time, money, labor), project "ownership" expires 3 years after data collection has ended (or whenever the original primary lead relinquishes their rights to the study, whichever comes first). At that point, Amy reserves the right to re-assign the project as needed to expedite publication. This policy is intended to avoid situations in which a dataset languishes for a long period of time, while still giving publication priority to the original primary lead. 

## Informal

To the extent that your time and interest allows, Amy supports people writing informal posts/threads on social media, blogging, etc. Effective and engaging science communication is a skill that takes time to develop, and your experiences at SAFS, UW, and beyond will provide ample opportunities for practice. Amy's only requirement is that anything you share adhere to our [Code of Conduct] and abide by the [Conversation Norms] agreed to with others.
